@PracticaAPI_HostAddress = https://localhost:7165

GET {{PracticaAPI_HostAddress}}/api/weatherforecast/
Accept: application/json

###

@id=20
GET {{PracticaAPI_HostAddress}}/api/weatherforecast/{{id}}

###
